# -*- coding: utf-8 -*-
"""ETL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zR5EB8boHdX3Xw-lw-T0-BhjNM9CU2x
"""



import pandas as pd

df = pd.read_csv('/content/healthcare_dataset.csv (1).zip')

# Display the first 5 rows of the DataFrame
display(df.head())

df1 = pd.read_csv('/content/appointments.csv')

display(df1.head())

# List of columns to drop
columns_to_drop = [
    'Blood Type',
    'Date of Admission',
    'Hospital',
    'Insurance Provider',
    'Billing Amount',
    'Room Number',
    'Admission Type',
    'Discharge Date',
    'Medication',
    'Test Results'
]

# Check if columns exist in the DataFrame before dropping
existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]

if existing_columns_to_drop:
    df_dropped = df.drop(columns=existing_columns_to_drop)
    print(f"DataFrame after dropping columns: {existing_columns_to_drop}")
    display(df_dropped.head())
else:
    print("None of the specified columns were found in the DataFrame.")
    print("Current columns are:", df.columns.tolist())



# List of columns to drop
columns_to_drop = [
   'slot_id',
    'scheduling_interval' , 'check_in_time' ,'start_time', 'end_time', 'sex' ,'age'
]

# Check if columns exist in the DataFrame before dropping
existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]

if existing_columns_to_drop:
    df_dropped = df.drop(columns=existing_columns_to_drop)
    print(f"DataFrame after dropping columns: {existing_columns_to_drop}")
    display(df_dropped.head())
else:
    print("None of the specified columns were found in the DataFrame.")
    print("Current columns are:", df.columns.tolist())



# List of columns to drop from the healthcare DataFrame
healthcare_columns_to_drop = [
    'Blood Type',
    'Date of Admission',
    'Hospital',
    'Insurance Provider',
    'Billing Amount',
    'Room Number',
    'Admission Type',
    'Discharge Date',
    'Medication',
    'Test Results'
]

# Check if columns exist in healthcare_df before dropping
existing_healthcare_columns = [col for col in healthcare_columns_to_drop if col in df1.columns]

if existing_healthcare_columns:
    healthcare_df_cleaned = df1.drop(columns=existing_healthcare_columns)
    print(f"Healthcare DataFrame cleaned by dropping: {existing_healthcare_columns}")
    display(healthcare_df_cleaned.head())
else:
    print("None of the specified healthcare columns were found in the DataFrame.")
    print("Current columns in healthcare_df are:", df1.columns.tolist())
    healthcare_df_cleaned = df1.copy() # Make a copy if no columns were dropped

# Add an 'index' column (starting from 1) to df_dropped
df_dropped['index'] = range(1, len(df_dropped) + 1)
print("df_dropped with new 'index' column:")
display(df_dropped.head())

# Add an 'index' column (starting from 1) to healthcare_df_cleaned
healthcare_df_cleaned['index'] = range(1, len(healthcare_df_cleaned) + 1)
print("healthcare_df_cleaned with new 'index' column:")
display(healthcare_df_cleaned.head())

# Merge the two cleaned DataFrames on the 'index' column
merged_df = pd.merge(df_dropped, healthcare_df_cleaned, on='index', how='inner')

print("Merged DataFrame (merged_df):")
display(merged_df.head())
print("Shape of the merged DataFrame:", merged_df.shape)

print("Cleaning 'merged_df' DataFrame:")
initial_rows_merged = len(merged_df)
merged_df_cleaned_nan = merged_df.dropna()
dropped_rows_merged = initial_rows_merged - len(merged_df_cleaned_nan)
print(f"Dropped {dropped_rows_merged} rows from 'merged_df'.")
display(merged_df_cleaned_nan.head())
print(f"New shape of 'merged_df_cleaned_nan': {merged_df_cleaned_nan.shape}\n")

print("Removing duplicate rows from 'merged_df_cleaned_nan':")
initial_rows_dedup = len(merged_df_cleaned_nan)
merged_df_deduplicated = merged_df_cleaned_nan.drop_duplicates()
duplicates_removed = initial_rows_dedup - len(merged_df_deduplicated)
print(f"Removed {duplicates_removed} duplicate rows.")
display(merged_df_deduplicated.head())
print(f"New shape of 'merged_df_deduplicated': {merged_df_deduplicated.shape}")

print("Original dtypes of merged_df_deduplicated:")
print(merged_df_deduplicated.dtypes)

# Columns to convert to datetime format
date_columns_to_convert = [
    'scheduling_date',
    'appointment_date'
]

for col in date_columns_to_convert:
    if col in merged_df_deduplicated.columns:
        try:
            # Convert to datetime
            merged_df_deduplicated[col] = pd.to_datetime(merged_df_deduplicated[col], errors='coerce')
            print(f"Successfully converted '{col}' to datetime.")
        except Exception as e:
            print(f"Could not convert '{col}' to datetime: {e}")
    else:
        print(f"Column '{col}' not found in DataFrame.")

print("\nUpdated dtypes of merged_df_deduplicated:")
print(merged_df_deduplicated.dtypes)

display(merged_df_deduplicated.head())

# Create 'appointment_day' column from 'appointment_date'
# Ensure 'appointment_date' is in datetime format first
if 'appointment_date' in merged_df_deduplicated.columns and pd.api.types.is_datetime64_any_dtype(merged_df_deduplicated['appointment_date']):
    merged_df_deduplicated['appointment_day'] = merged_df_deduplicated['appointment_date'].dt.day_name()
    print("Created 'appointment_day' column:")
    display(merged_df_deduplicated[['appointment_date', 'appointment_day']].head())
else:
    print("'appointment_date' column is not available or not in datetime format. Please ensure it's converted first.")

display(merged_df_deduplicated.head())

print("Removing outliers from 'waiting_time' where value > 180:")
initial_rows_outliers = len(merged_df_deduplicated)

# Filter out rows where 'waiting_time' is greater than 180
merged_df_deduplicated_cleaned_outliers = merged_df_deduplicated[merged_df_deduplicated['waiting_time'] <= 180]

outliers_removed = initial_rows_outliers - len(merged_df_deduplicated_cleaned_outliers)
print(f"Removed {outliers_removed} rows with 'waiting_time' greater than 180.")

display(merged_df_deduplicated_cleaned_outliers.head())
print(f"New shape of DataFrame after removing outliers: {merged_df_deduplicated_cleaned_outliers.shape}")


import pandas as pd

new_df = pd.read_excel('/content/satisfaction audit.xlsx')

# Display the first 5 rows of the new DataFrame
display(new_df.head())

# Add an 'index' column (starting from 1) to new_df
new_df['index'] = range(1, len(new_df) + 1)
print("new_df with new 'index' column:")
display(new_df.head())

# Merge new_df with the previously cleaned and merged DataFrame on the 'index' column
final_merged_df = pd.merge(merged_df_deduplicated_cleaned_outliers, new_df, on='index', how='inner')

print("Final Merged DataFrame (final_merged_df):")
display(final_merged_df.head())
print("Shape of the final merged DataFrame:", final_merged_df.shape)

print("Original dtypes of final_merged_df:")
print(final_merged_df.dtypes)

columns_to_convert_to_numeric = [
    'appointment_id',
    'appointment_duration',
    'waiting_time',
    'patient_id',
    'Age',
    'Satisfaction rate'
]

for col in columns_to_convert_to_numeric:
    if col in final_merged_df.columns:
        try:
            # Convert to numeric
            final_merged_df[col] = pd.to_numeric(final_merged_df[col], errors='coerce')
            print(f"Successfully converted '{col}' to numeric.")
        except Exception as e:
            print(f"Could not convert '{col}' to numeric: {e}")
    else:
        print(f"Column '{col}' not found in DataFrame.")

print("\nUpdated dtypes of final_merged_df:")
print(final_merged_df.dtypes)

display(final_merged_df.head())

# Ensure 'appointment_time' is in a proper datetime format first
if 'appointment_time' in final_merged_df.columns:
    # Convert to datetime
    final_merged_df['appointment_time'] = pd.to_datetime(final_merged_df['appointment_time'], errors='coerce')
    # Create 'appointment_hour' column
    final_merged_df['appointment_hour'] = final_merged_df['appointment_time'].dt.hour
    print("Created 'appointment_hour' column:")
    display(final_merged_df[['appointment_time', 'appointment_hour']].head())
else:
    print("'appointment_time' column not found in the DataFrame.")

display(final_merged_df)

# List of columns to drop
columns_to_drop_final = ['age', 'sex', 'scheduling_date', 'scheduling_interval', 'slot_id', 'start_time',	'end_time', 'check_in_time']

# Check if columns exist in the DataFrame before dropping
existing_columns_to_drop_final = [col for col in columns_to_drop_final if col in final_merged_df.columns]

if existing_columns_to_drop_final:
    final_merged_df = final_merged_df.drop(columns=existing_columns_to_drop_final)
    print(f"Final DataFrame after dropping columns: {existing_columns_to_drop_final}")
    display(final_merged_df.head())
else:
    print("None of the specified columns were found in the Final DataFrame.")
    print("Current columns are:", final_merged_df.columns.tolist())

output_file_name = 'final_cleaned_merged_data.xlsx'
final_merged_df.to_excel(output_file_name, index=False)
print(f"DataFrame successfully saved to {output_file_name}")